### ISSUE TITLE
Support compilation of multiple relations as a sequence

### ISSUE THREAD

**Issue by rtpsw** [ibis-project/ibis-substrait#111]
Currently, the Substrait compiler compiles only a single TableExpr as one relation, such as projection or aggregation. The proposal is to add support for multiple relations that are connected as a sequence of table operations (DAG connections would be handled in a separate issue).

**Comment by rtpsw** [comment]
Here is a proposed design:

1. Add `WriteRel` in the protobuf definitions.
2. Add a new class RelsExpr derived from Expr that would collect multiple relations (e.g., projection followed by writing) using a fluent API.
3. Add support in the Substrait compiler for handling multiple relations as a sequence of table operations.

**Comment by icexelloss** [comment]
@rtpsw can you give a bit details about what currently isn't quite working?

**Comment by cpcloud** [comment]
There is support in substrait itself for multiple relations: https://github.com/substrait-io/substrait/blob/main/proto/substrait/plan.proto#L34, but `ibis-substrait` only supports a single relation, mostly because it's not entirely clear what the meaning of multiple relations is.

**Comment by rtpsw** [comment]
Agreed. I noticed this and my thinking was that a relation's input (single or left/right) could be changed to be either a `Rel` or a (numeric index) reference to a previous relation in the plan, where the default could be the last relation defined in the plan so as to get a sequence of table operations.

**Comment by rtpsw** [comment]
@cpcloud, at first I'm interested in validating the proposed design, or reaching agreement on an alternative design. I would likely take on the implementation.

**Comment by cpcloud** [comment]
@rtpsw Can we close this out, or is there more to discuss?

**Comment by rtpsw** [comment]
I currently do not have a pressing need for this, so I'm OK with closing this. If you have given this some thought, perhaps you can post your opinion about the proposed design, in case this gets reopened later.

**Comment by cpcloud** [comment]
@rtpsw Can you give a sketch of what the API might look like here? I'm not following whether multiple relations here means "a single table expression composed of one or more subqueries" or literally a list of TableExprs.

**Comment by rtpsw** [comment]
A `PlanRel` includes a single relation, which is [one of read, filter, fetch, etc](https://github.com/substrait-io/substrait/blob/main/proto/substrait/algebra.proto#L306-L321), so a plan with multiple `PlanRel` would have several of these. The (default) semantics I have in mind is wiring-relations-in-sequence. That is, if the plan has 3 `PlanRel` containing `ReadRel`, `FilterRel`, and `AggregateRel` respectively, then the functional semantics is `aggregate(filter(read(...), ...), ...)`. I think the Ibis API for this should look something like `ibis.table(...).filter(...).aggregate(...)`. I'm leaving the more complex semantics of wiring-relations-as-a-DAG ([mentioned above](https://github.com/ibis-project/ibis-substrait/issues/111#issue-1168741600)) out of scope here.

**Comment by cpcloud** [comment]
I think what you are describing is already the case. Since relations can be nested, you can compose them as you like and there can be arbitrarily many `Rel`s nested below the root.

**Comment by rtpsw** [comment]
Indeed the existing nested-relations syntax is semantically equivalent but it cannot be extended to a DAG.
