### ISSUE TITLE
Adding a new committer

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis-substrait#1142]
I don't know if we have a procedure / governance for adding members to Ibis' "side projects", but in any case, I would like to nominate @tokoko as a committer for `ibis-substrait` -- Tornike has been active on the project, _very_ helpfully ported ibis-substrait to use Ibis 9.x and has added a suite of parity checks to confirm that consumers produce the same results given a substrait plan.

cc @cpcloud @jcrist @kszucs @tswast

**Comment by cpcloud** [comment]
+1, would be great to have you @tokoko!

**Comment by jcrist** [comment]
+1!

**Comment by gforsyth** [comment]
:tada: The ayes have it

**Comment by tokoko** [comment]
@gforsyth thanks for the nomination. I'd gladly help as much as I can.
