### ISSUE TITLE
Expand table expression to its columns

### ISSUE THREAD

**Issue by rtpsw** [ibis-project/ibis-substrait#184]
This is a proposal for making the handling of Substrait selections easier for Substrait consumers. Currently, Substrait consumers, such as Arrow, need to handle schema computations during Substrait deserialization in order to infer the columns of a table expression, which are needed for setting up a projection. In Arrow, such computations are not supported because schemata instances are only created after deserialization. By having Ibis-Substrait expand the table expression to its columns, a Substrait consumer can directly construct the corresponding projection.

**Comment by cpcloud** [comment]
Closed by #185.
