### ISSUE TITLE
Support AsofJoin operation

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis-substrait#332]
Recently Asof Join has been added to Acero and I'd like to open an issue for supporting this via ibis/ibis-substrait.

@rtpsw has done some initial investigation and wrote up the finding below:

Ibis and Substrait both need some enhancements for integration with Arrow's AsofJoinNode.

Ibis defines an [AsOfJoin operation](https://github.com/ibis-project/ibis/blob/693005d5046eaace37b8c6d6d7d09104de99fe9b/ibis/expr/operations/relations.py#L241) deriving from a [Join operation](https://github.com/ibis-project/ibis/blob/693005d5046eaace37b8c6d6d7d09104de99fe9b/ibis/expr/operations/relations.py#L167). Its attributes are not aligned with those of AsofJoinNodeOption in Arrow:

* The Ibis operation supports only a single right table whereas the Arrow node support multiple right tables.
* The Ibis operation support predicates whereas the Arrow node does not.
Perhaps for now a good way to bridge the gap, either changing or deriving an Ibis operation, is by:

extending the right (or adding a more_right) attribute of the Ibis operation to accept a list of tables
adding an on attribute to the Ibis operation
not supporting predicates in the Arrow one
Substrait only has a [JoinRel relation](https://github.com/substrait-io/substrait/blob/main/proto/substrait/algebra.proto#L154) but not an AsOfJoin one. This gap can be bridged by extending (or adding a new relation extending) JoinRel relation with on and tolerance fields.

**Comment by icexelloss** [comment]
I think at the high level, the "shape" of asof join in ibis and Acero are different. I think the shape that supports multiple right tables are probably more general. 

It's probably not to hard to change ibis asof join API signature to support multiple right tables (the `right` parameter can take a list of tables) and then the translation to substrait is more nature (assuming we have the multiple right tables in the substrait plan for asof join). 

Thoughts?

**Comment by rtpsw** [comment]
Note that [`AsofJoin` op](https://github.com/ibis-project/ibis/blob/18e7f9555c3bf8c602ebcaef0188e03d7b0bd7ee/ibis/expr/operations/relations.py#L256) in Ibis, which is defined as a left join operation, is derived from a `Join` op, which is limited to a left and right table. It may make sense to define a multi-table join op for the former to derive from.

An Ibis `AsofJoin` design point that is not clear to me: The [Ibis execution of `AsofJoin`](https://github.com/ibis-project/ibis/blob/10a659d66145403c872ec176b8a739613f0061e7/ibis/backends/pandas/execution/join.py#L139) appears to support [multiple `on` columns](https://github.com/ibis-project/ibis/blob/10a659d66145403c872ec176b8a739613f0061e7/ibis/backends/pandas/execution/join.py#L141) via the [predicates extraction](https://github.com/ibis-project/ibis/blob/10a659d66145403c872ec176b8a739613f0061e7/ibis/backends/pandas/execution/join.py#L158), though [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge_asof.html)) (like Acero) only supports a single `on` column.

**Comment by rtpsw** [comment]
Looking into [this](https://github.com/ibis-project/ibis-substrait/issues/332#issuecomment-1229396569) a bit more, I suspect there is a larger design issue at play here. The Ibis predicates could either be handled by a (pandas) backend, where they are worked out by a column matching logic, or would be embedded in a Substrait plan via translation (per the current issue). This embedding effectively shift the column matching logic to a Substrait consumer, such as Acero. The need to implement the column matching logic again appears to be a design problem that should likely be considered first.

**Comment by icexelloss** [comment]
@cpcloud Any thoughts? I think the easiest to start with is to keep the ibis API unchanged for now but allow substrait protobuf to contain a list of right tables, and make it a list of 1 right tables for ibis asof join.

Internally, we do not use ibis asof join node directly so it's not hard for us to create custom translation rule for our internal AsofJoin node to create a list of right side tables.

**Comment by cpcloud** [comment]
@icexelloss An as of join that accepts multiple right tables seems fine to me. It's a bit different from the rest of the join operators, but I don't think that should matter much.

**Comment by cpcloud** [comment]
We would like to change joins to be variadic internally in ibis, but I'm not sure that'll be ready/done by the time you need this functionality elsewhere and it sounds like you've got your own internal node for this anyway :)

**Comment by rtpsw** [comment]
I created [a PR](https://github.com/substrait-io/substrait/pull/331) for this.

**Comment by icexelloss** [comment]
We can close this for now - We moved forward with an internal AsofJoin node.
