### ISSUE TITLE
Issue with platformdirs in the dependency

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis-substrait#337]
Hi,

I am trying to import ibis-substrait into our build system and hit an issue with `platformdirs`. It seems it is built with "hatchling" and our internal system doesn't understand "hatchling" build system.

After looking at the substrait code, I didn't find where it was being used in the source code, perhaps this is a dev dependency and not a regular dependency?

**Comment by icexelloss** [comment]
From what I understand, the actual dependencies are just `protobuf` and `ibis-framework`? (I actually don't see where sqlalchemy is used either"

**Comment by gforsyth** [comment]
Hey @icexelloss -- I'm cleaning up the dependencies now.  `hatch` and `hatchling` are part of the group of ever increasing PEP517-compatible build systems.  But yes, the only dependencies for regular usage should be `ibis-framework` and `protobuf`.  We are still using `packaging` to handle some ibis 2.x to 3.x stuff but I'm about to rip that out.
