### ISSUE TITLE
How do I generate the substrait protobuf files with a lower protobuf version

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis-substrait#342]
I am importing ibis-substrait codebase into our internal system and hit an issue - Internally we are using protobuf 3.19 which does not work with the protobuf source files in ibis-substrait (I think required >= 3.20). I think there are two ways to move forward:

(1) Upgrade our internal protobuf. I am looking into this but could potentially be difficult to do quickly.
(2) Generate substrait protobuf files myself with a 3.19 and use those files instead of the ones in this repo. I think this gives me move forward faster.

My question is, about (2), is there something already exists in this repo that I can use to generate those protobuf classes?

**Comment by gforsyth** [comment]
Hey @icexelloss -- longer-term, I would definitely recommend that you upgrade `protobuf` -- I think substrait is standardizing around the version defined in their `buf` spec and that's `3.20`.

Shorter-term, this is the shell script that gets run to generate the python stubs:
https://github.com/ibis-project/ibis-substrait/blob/main/shell.nix#L27-L48

the contents of `/.proto` is a clone of the upstream `substrait-io/substrait` repo

**Comment by icexelloss** [comment]
Thanks for the pointer! I will give it a shot.

**Comment by icexelloss** [comment]
Close this now since I think I have what I need. Thx!
