### ISSUE TITLE
substrait_validator in test_tpch.py

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis-substrait#343]
Hi,

I am testing ibis-substrait and notice test_tpch.h is failing because it cannot find `substrait_validator` - out of curiosity what is this package?

**Comment by gforsyth** [comment]
https://github.com/substrait-io/substrait-validator

It validates substrait plans against the spec

**Comment by cpcloud** [comment]
Should we make this an optional dependency?

**Comment by icexelloss** [comment]
Thanks for the reponse

**Comment by gforsyth** [comment]
@cpcloud -- it's listed under the dev dependencies.  Or were you proposing adding it as an `extras_require` option?

**Comment by cpcloud** [comment]
Ah, I think I misunderstood. Thanks for clearing it up.
