### ISSUE TITLE
feat: add math functions to mapping

### ISSUE THREAD

**Issue by wjones127** [ibis-project/ibis-substrait#368]
Functions such as `sqrt` and `pow` could be added to https://github.com/ibis-project/ibis-substrait/blob/main/ibis_substrait/compiler/mapping.py

https://ibis-project.org/docs/3.2.0/api/expressions/numeric/#ibis.expr.types.numeric.NumericColumn.corr

Many of these are available in: https://github.com/substrait-io/substrait/blob/main/extensions/functions_arithmetic.yaml

**Comment by gforsyth** [comment]
Closed via #350
