### ISSUE TITLE
feat: default literals to nullable=False

### ISSUE THREAD

**Issue by wjones127** [ibis-project/ibis-substrait#369]
From #256:

> I'm not sure what the downsides are to defaulting to nullable literals are but I think we can start with this.

The downsides are that Acero does not handle them. See:

 * https://github.com/apache/arrow/blob/master/cpp/src/arrow/engine/substrait/expression_internal.cc#L299-L302
 * https://issues.apache.org/jira/browse/ARROW-15540

**Comment by gforsyth** [comment]
yeah, that's a downside!

I think at the very least we should be pulling nullability information from ibis so the ibis expression can specify non-nullable and then that gets translated correctly

**Comment by jcrist** [comment]
Should be fixed by #373.
