### ISSUE TITLE
Custom data source node doesn't work with selection

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis-substrait#393]
During testing of projection, we noticed that our custom data source node that doesn't work with the mapper counter logic here:

https://github.com/ibis-project/ibis-substrait/blob/main/ibis_substrait/compiler/translate.py#L743

This is because our internal data source only inherent from ibis `TableNode` but not `UnboundTable` (internally we have basically our own class for Data source node and we do not use ibis `UnboundTable` because at the time it seemed `UnboundTable` were used for different purpose).

This is from the discussion here:
https://github.com/ibis-project/ibis-substrait/blob/main/ibis_substrait/compiler/translate.py#L743

**Comment by icexelloss** [comment]
Our internally data source basically defined as 
```
class IbisLeafTableNode(TableNode, HasSchema)
```
Other data source node inherent from this class

**Comment by gforsyth** [comment]
I would argue that `UnboundTable`s are inherently non-specific.  They allow for construction of expressions and Substrait plans without any connection to the data that the consumer engine will execute on.

I'm not sure about using `PhysicalTable` -- the only thing separating `PhysicalTable` from `UnboundTable` is that `UnboundTable` requires both a `schema` and a `name`, which are both things that we want anyway.

I wonder if we implemented ibis-project/ibis#4536 if that would solve this issue?  In the interim, you could probably write something specific to your style of tables.  We do this in `tpc-queries` to generate unbound tables from `duckdb` tables: 
```python
def unbound_from_duckdb(table):  # noqa: D103
    return ibis.table(
        list(zip(table.columns, map(parse_type, table.dtypes))), name=table.alias
    )
```

**Comment by jcrist** [comment]
@icexelloss what substrait do you generate for your custom table source? If your custom data source maps to a `NamedTable` in substrait, then I'd argue that an `UnboundTable` is the proper type. If it's something else (e.g. one of https://github.com/substrait-io/substrait/blob/main/proto/substrait/algebra.proto#L67-L72), then we might use `PhysicalTable` or define a new op type in `ibis-substrait` that y'all could subclass from that might work.

**Comment by icexelloss** [comment]
I tried to inherit internal node to `UnboundTable` but get an attribute conflict - I think this is because we either defined schema as a method/property on our nodes (we use _schema to store the actual schema) and/or because of the `name` attribute. 

I think using UnboundTable is maybe OK but perhaps `UnboundTable` should be a pure interface that defines exposes the `schema` and let the user that extend the interface decide how they want to implement it, rather than force the implementation / attributed in the `UnboundTable` class (perhaps same for `name`)

**Comment by icexelloss** [comment]
> what substrait do you generate for your custom table source? If your custom data source maps to a NamedTable in substrait, then I'd argue that an UnboundTable is the proper type.
Yes we current map this to `NamedTable` but this might be temporary - In the future we might consider using a substrait extension type rather than the NamedTable.

**Comment by icexelloss** [comment]
>  In the interim, you could probably write something specific to your style of tables.
This is less ideal because internally we already have an ibis node class that represents our custom data source `IbisLeafTableNode` that already works with Pandas/Spark backends. Turning `IbisLeafTableNode -> UnboundTable` is additional customization that we need to do for the Acero backend and increases internally complexity, since now the ibis node for the same logical thing is different among backends. This can be done but add another layer of complexity.

**Comment by jcrist** [comment]
> I tried to inherit internal node to `UnboundTable` but get an attribute conflict - I think this is because we either defined schema as a method/property on our nodes (we use _schema to store the actual schema) and/or because of the `name` attribute conflict.

I think trying to get this working would be the best path forward for now. Especially since you're currently generating `NamedTable` nodes for your custom type, this seems the most correct option.

Can you post more information about the errors you're seeing, or (better yet) a code snippet with the subclass that produces those errors?

**Comment by icexelloss** [comment]
Are their any tactical solution that we might be able to use to solve this?
Ideally changes local to ibis substrait

**Comment by jcrist** [comment]
I've pushed up a simple but non-ideal solution in #394. Can you test that to see if it resolves your problem?

In the long run it would be better to adapt your code, but I understand that can be tricky to do under a time crunch.

**Comment by icexelloss** [comment]
Thanks for the tactile fix - I will test it on Monday and report back

**Comment by icexelloss** [comment]
I tested internally and this works. If there is no objection I'd suggest we merge this patch and think more about long term solutions for this.

**Comment by icexelloss** [comment]
Thank you!
