### ISSUE TITLE
Add support for `Log`

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis-substrait#407]
Ibis-substrait currently supports `log10`, `log2`, and `ln`, but not `log`. AFAICT this is `logb` (https://github.com/substrait-io/substrait/blob/main/extensions/functions_logarithmic.yaml#L95) in substrait.

**Comment by gforsyth** [comment]
This should be straightforward and quick to add -- we need a rule to dispatch on `ops.Log` and Ibis (I believe) handles setting the log base to `e` if it isn't specified.
