### ISSUE TITLE
Add support for `Clip`

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis-substrait#409]
`substrait` doesn't have a builtin method for this AFAICT, but the functionality may be composable from other builtin methods?

**Comment by gforsyth** [comment]
We can do this with a kind of gross `CASE WHEN` and we'll probably have to handle nullability, too

**Comment by gforsyth** [comment]
this is a little more involved than `FloorDivide` and `Log` but it _should_ be manageable without a huge lift.  Ideally, `clip` will be added to the substrait extensions which will simplify the implementation on our end.

**Comment by cpcloud** [comment]
Can't we turn this into a translation of:

```
least(greatest(x, lower), upper)
```
?

**Comment by amoeba** [comment]
I _think_ Substrait doesn't have least/greatest yet but there's [a PR](https://github.com/substrait-io/substrait/pull/247). I also filed an issue on the Substrait repo to [discuss Clip](https://github.com/substrait-io/substrait/issues/366).

**Comment by icexelloss** [comment]
> Can't we turn this into a translation of:
> 
> ```
> least(greatest(x, lower), upper)
> ```
> 
> ?

I think we can do
```
(col > min).iflese((col <= max).ifelse(col, max), min)
```
?

**Comment by cpcloud** [comment]
@icexelloss That seems reasonable until least/greatest or an explicit clip function is supported in substrait.
