### ISSUE TITLE
Question about protobuf version (ibis-substrait requires protobuf 3.20.1)

### ISSUE THREAD

**Issue by drin** [ibis-project/ibis-substrait#484]
I was able to write substrait using the following versions in one repo:
```python
duckdb = "^0.6.1"
ibis-framework = "^4.0.0"
pyarrow = "^10.0.1"
duckdb-engine = "^0.6.8"
ibis-substrait = "^2.19.0"
```

I have a separate repo where I started from substrait and have the following dependencies:
```python
protobuf = "^4.21.12"
ibis = "^3.2.0"
```

Understandably, I came across this error (my repo is called `encoder-substrait` for now):
```bash
Because no versions of ibis-substrait match >2.19.0,<3.0.0
 and ibis-substrait (2.19.0) depends on protobuf (3.20.1), ibis-substrait (>=2.19.0,<3.0.0) requires protobuf (3.20.1).
So, because encoder-substrait depends on both protobuf (^4.21.12) and ibis-substrait (^2.19.0), version solving failed.
```

I can downgrade just to play around with things, but just wondering if updating protobuf is on the roadmap or if there are version-related problems I should be aware of? I saw the following comment in the `pyproject.toml`, but it doesn't seem relevant for a newer version of protobuf:
```python
# protobuf==3.20 C extensions aren't compatible with 3.19.4
```

**Comment by drin** [comment]
(also, if there is somewhere better to these questions, please let me know! I wasn't sure so I've just been putting them here)

**Comment by drin** [comment]
oof, I just realized that the protobuf version is loosely based on the version specified by whatever compiles the protobuf definitions, yeah?

https://github.com/substrait-io/substrait/blob/main/buf.gen.yaml#L9-L10:
```yaml
  - remote: buf.build/protocolbuffers/plugins/python:v3.20.0-1
    out: gen/proto/python
```

**Comment by gforsyth** [comment]
Hey @drin -- this is a fine place to ask questions like these.  And yeah, I think you found the main reason.  `protobuf` is technically "backwards compatible", at least within major versions.  This isn't always true, but that's the nominal guarantee.  So we track whichever version of `protobuf` the upstream `substrait` project is using.  We can probably relax the hard pin to allow higher versions, although I'm not sure if allowing versions `>=4` will work

**Comment by drin** [comment]
thanks!
