### ISSUE TITLE
bug: count_distinct is handled incorrectly

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis-substrait#561]
### What happened?

There is no `count_distinct` scalar or aggregate extension function defined.
Instead, we should call `count` on an aggregate that specifies unique inputs.

### What version of ibis-substrait are you using?

main

**Comment by tokoko** [comment]
This was most likely fixed in #1034. I was unable to add it to parity tests though, because acero substrait consumer doesn't seem to know the distinction between `count` and `count_distinct`.

**Comment by gforsyth** [comment]
I'm good closing this out as fixed -- we can revisit if that turns out to be incorrect.
