### ISSUE TITLE
Question about ibis table selector support

### ISSUE THREAD

**Issue by drin** [ibis-project/ibis-substrait#564]
Is there interest in substrait extensions or adding to substrait core support for table selectors?

I am primarily interested in being able to do a projection programmatically (using slice notation), but I expect table selector support to introduce similar mechanisms.

**Comment by gforsyth** [comment]
You mean selectors as in something like `mytable.select(s.numeric())` projecting out all the columns with a numeric dtype?

At first glance, I'm not sure that's something that would belong in substrait -- the schema of the table is defined in the plan, and when translating to substrait, you would be able to take the result of any selector projection to grab the appropriate indices for the selected columns.

But I'm just one person -- you can throw this question to the mailing list or post on the Substrait slack.

**Comment by cpcloud** [comment]
Table selectors (at least in their current incantation) are meant to be pure syntactic sugar/shorthand.

It could be interesting to think about a cross-system way to express them, but they're not nearly as widespread as the other things that substrait deals with.

**Comment by drin** [comment]
> ...as in something like mytable.select(s.numeric()) ...?

yes

> but they're not nearly as widespread as the other things that substrait deals with.

This was partially my motivation for asking here first rather than the substrait channel, since this type of syntax isn't available in SQL at all unless you join against the table schema as a table itself. Which, I don't think substrait currently supports, so that would have to be its own addition as well with the same functional goal (I think).

> when translating to substrait, ...take the result of any selector projection to grab the appropriate indices for the selected columns
> ...
> selectors ... are meant to be pure syntactic sugar/shorthand.

Hm, so from this, I looked at some sample substrait again and it seems like it assigns a unique identifier to every column reference in a query? In the case where those references exist, then I think using those indices makes sense. But I kind of feel like having thousands or millions of columns makes this approach unwieldy.

Looking at the substrait spec again, I think what would be useful is [masked-complex-expression][spec-exprmask]-like syntax for columns (I think that expression is only for nested columns? unless I'm misunderstanding the point of the top-level `struct:` reference there).

But either way, I'll take it to the substrait community since you both answered my question. Thanks!


[spec-exprmask]: https://substrait.io/expressions/field_references/#masked-complex-expression
