### ISSUE TITLE
feat: add support for cross joins

### ISSUE THREAD

**Issue by vibhatha** [ibis-project/ibis-substrait#594]
### What happened?

When using the ibis-substrait compiler to convert the following experssion to a Substrait plan

```python
import ibis
from ibis_substrait.compiler.core import SubstraitCompiler
from google.protobuf import json_format

tA = ibis.table([("a", "int"), ("b", "date"), ("c", "int32")], "tA",)
tB = ibis.table([("a", "int"), ("b", "date"), ("c", "int32")], "tB",)

expr = tA.cross_join(tB)
compiler = SubstraitCompiler()
proto = compiler.compile(expr)
json_plan = json_format.MessageToJson(proto)
```
I am getting an error. Logged below.

### What version of ibis-substrait are you using?

2.28.1

### What substrait consumer(s) are you using, if any?

Ibis

### Relevant log output

```sh
Traceback (most recent call last):
  File "/home/asus/sandbox/ibis-substrait/bug/test.py", line 10, in <module>
    proto = compiler.compile(expr)
  File "/home/asus/sandbox/ibis-substrait/bug/ibis-substrait/lib/python3.10/site-packages/ibis_substrait/compiler/core.py", line 199, in compile
    input=translate(expr.op(), expr=expr, compiler=self, **kwargs),
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/asus/sandbox/ibis-substrait/bug/ibis-substrait/lib/python3.10/site-packages/ibis_substrait/compiler/translate.py", line 804, in selection
    relation = translate(
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/asus/sandbox/ibis-substrait/bug/ibis-substrait/lib/python3.10/site-packages/ibis_substrait/compiler/translate.py", line 1000, in join
    functools.reduce(operator.and_, predicates),
TypeError: reduce() of empty iterable with no initial value
```

**Comment by vibhatha** [comment]
cc @gforsyth

**Comment by gforsyth** [comment]
Hey @vibhatha -- thanks for the report!  It looks like the initial error here is because cross joins don't have a `predicate` and we're expecting one.  This change fixes that up:

```
diff --git a/ibis_substrait/compiler/translate.py b/ibis_substrait/compiler/translate.py
index 14f4a0b..77bd922 100644
--- a/ibis_substrait/compiler/translate.py
+++ b/ibis_substrait/compiler/translate.py
@@ -975,7 +975,9 @@ def join(
                 compiler=compiler,
                 child_rel_field_offsets=child_rel_field_offsets,
                 **kwargs,
-            ),
+            )
+            if predicates
+            else None,
             type=_translate_join_type(op),
         )
     )
```

but the next bit to implement is that we currently don't have a translation rule for cross joins.  Is that something you'd be interested in implementing?

**Comment by vibhatha** [comment]
@gforsyth I would like to help with this. Where should I start first to learn a few things? Or is this a complex change that need more expertise on the domain (Ibis/Ibis-Substrait)?

**Comment by gforsyth** [comment]
I don't think it will be very complex. 

To start, I would suggest getting a dev environment set up, using either conda or nix.

Then I'd suggest looking over `translate.py` to start getting an idea of how the project works.

It's helpful to have some familiarity with Ibis, too. But the main thing to know is that an Ibis expression can be decomposed into a sequence of operations, and those operations are the targets that each of the translate rules dispatches on.

**Comment by gforsyth** [comment]
Also, feel free to ask questions here! There are very limited docs (sorry about that)

**Comment by vibhatha** [comment]
Thanks Gil, I will look into this.

**Comment by gforsyth** [comment]
Hey @vibhatha -- let me know if you're blocked on this and I'm happy to help out.
