### ISSUE TITLE
feat: Support extension function outside of substrait spec

### ISSUE THREAD

**Issue by icexelloss** [ibis-project/ibis-substrait#597]
Substrait function is defined by the function uri + function name. 

Currently, all functions in ibis-strait comes from https://github.com/substrait-io/substrait/tree/main/extensions

There is a need to add function that of outside of main substrait spec. e.g., during https://github.com/apache/arrow/pull/35513#issuecomment-1544181944 to add first and last aggregation in Acero, we recognized that there is a need to communicate functions with alternatively uri, e.g., `urn:arrow:substrait_simple_extension_function` that is Acero specific. Other than the "first and last" function, we are also thinking about adding "floor and ceil" function for timestamp columns (e.g., in pandas, this is `s.dt.ceil` and `s.dt.floor`).

This ask here is that if we can allow an mechanism to support this. Currently, we can get this working by implementing some mechanism in our downstream codebase, and effectively registering first/last doing sth similar to this (https://github.com/ibis-project/ibis-substrait/blob/main/ibis_substrait/compiler/mapping.py#L183), but apparently that uses private functions in ibis-substrait and not a great solution.

@rtpsw Can share more details on what is done internally and we can discuss if we can have a better way to do this in ibis-substrait.

**Comment by gforsyth** [comment]
Hey @icexelloss -- what's the issue with using `register_extension_yaml`?  I added that with exactly this use-casein mind.

**Comment by rtpsw** [comment]
See [my response in another thread](https://github.com/ibis-project/ibis-substrait/pull/596#issuecomment-1548003482). Let's pick one of the threads for this discussion.

**Comment by gforsyth** [comment]
I think the most expedient way to handle this is to add in some kind of `override` kwarg that will allow passing in a custom `uri` that isn't constructed from the file path.

**Comment by icexelloss** [comment]
> I think the most expedient way to handle this is to add in some kind of override kwarg that will allow passing in a custom uri that isn't constructed from the file path.

Yeah I think this could work. Alternatively we can also allow `register_extension_yaml` to take an uri parameter and move the logic (https://github.com/ibis-project/ibis-substrait/blob/main/ibis_substrait/compiler/mapping.py#LL198C28-L198C52)  to caller side https://github.com/ibis-project/ibis-substrait/blob/88723a19b82a91ef04e3c148f9329ec4458b4ecc/ibis_substrait/compiler/mapping.py#L202

**Comment by rtpsw** [comment]
> Hi @rtpsw can we please use this thread for dsicussion and close the other thread? [issue](https://github.com/ibis-project/ibis-substrait/pull/596)

That PR is marked as a draft and is not obsolete; it's just waiting for first/last to be added to the Substrait spec. We can continue the discussion about extension functions here.

**Comment by icexelloss** [comment]
@gforsyth Do you have a preferred solution/API? Would like to get this going so we can support this proper and remove the internal hack.

**Comment by icexelloss** [comment]
> it's just waiting for first/last to be added to the Substrait spec.
@rtpsw What do you mean by "waiting for first/last to be added to the Substrait spec"? Do you mean for first/last to be supported as standard function and not arrow/acero extension functions?

**Comment by rtpsw** [comment]
> @rtpsw What do you mean by "waiting for first/last to be added to the Substrait spec"? Do you mean for first/last to be supported as standard function and not arrow/acero extension functions?

My understanding is that it is likely first/last would be added to the Substrait spec. In this case, the code here would be useful. Until then, I marked the current PR as a draft. In the meantime, we're proceeding with first/last as extension functions.

**Comment by gforsyth** [comment]
> @gforsyth Do you have a preferred solution/API? Would like to get this going so we can support this proper and remove the internal hack.

I think a `uri` override kwarg makes sense.
