### ISSUE TITLE
Unable to load an ibis-generated substrait plan in subtrait-java

### ISSUE THREAD

**Issue by JosepSampe** [ibis-project/ibis-substrait#703]
I'm trying to load into a [substrait-java](https://github.com/substrait-io/substrait-java) Plan an ibis-generated substrait plan, but it seems it is unable to map the `sum` (and possibly others) function.

On the python side I have this code that ends up creating an `ibis.prop` file:
```python
from ibis_substrait.compiler.core import SubstraitCompiler
from google.protobuf import json_format
import ibis

if __name__ == '__main__':
    t = ibis.table(
        [("a", "string"), ("b", "float"), ("c", "float"), ("d", "int64"), ("e", "int64")],
        "t",
    )

    expr = t.group_by(["a", "b"]).aggregate([t.c.sum().name("suma")]).select("b", "suma")
    # expr = t.group_by(["a", "b"]).select("b") #  <- The plan generated from this expr is properly loaded in substrait-java
    ibis.show_sql(expr)

    compiler = SubstraitCompiler()
    plan = compiler.compile(expr)

    print(json_format.MessageToJson(plan))

    with open("ibis.proto", "wb") as f:
        f.write(plan.SerializeToString())
```

On the java side, I'm doing this:
```java
SimpleExtension.ExtensionCollection extensions = SimpleExtension.loadDefaults();
FileInputStream fis = new FileInputStream("ibis.proto");
io.substrait.proto.Plan protoPlanLoaded = io.substrait.proto.Plan.parseFrom(fis);
ProtoPlanConverter protoPlanConverter = new ProtoPlanConverter(extensions);
Plan sPlan = protoPlanConverter.from(protoPlanLoaded); // <- It fails here
...
```

The exception I get is this:
```
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected aggregate function with key sum. The namespace /functions_arithmetic.yaml is loaded but no aggregate function with this key was found.
	at io.substrait.extension.SimpleExtension$ExtensionCollection.getAggregateFunction(SimpleExtension.java:693)
	at io.substrait.extension.AbstractExtensionLookup.getAggregateFunction(AbstractExtensionLookup.java:35)
	at io.substrait.relation.ProtoRelConverter.newAggregate(ProtoRelConverter.java:378)
	at io.substrait.relation.ProtoRelConverter.from(ProtoRelConverter.java:72)
	at io.substrait.relation.ProtoRelConverter.newProject(ProtoRelConverter.java:341)
	at io.substrait.relation.ProtoRelConverter.from(ProtoRelConverter.java:84)
	at io.substrait.plan.ProtoPlanConverter.from(ProtoPlanConverter.java:40)
```

Checking the plans, I can see that the plan generated using ibis contains this:
```json
 "extensionUris": [
    {
      "extensionUriAnchor": 1,
      "uri": "/functions_arithmetic.yaml"
    }
  ],
  "extensions": [
    {
      "extensionFunction": {
        "extensionUriReference": 1,
        "functionAnchor": 1,
        "name": "sum"
      }
    }
  ],
```

While if I generate the same plan using substrait-java (using `SqlToSubstrait()`), the plan contains this:
```json
  "extensionUris": [
    {
      "extensionUriAnchor": 1,
      "uri": "/functions_arithmetic.yaml"
    }
  ],
  "extensions": [
    {
      "extensionFunction": {
        "extensionUriReference": 1,
        "name": "sum:fp32"
      }
    }
  ],
```

Note that in ibis the function is named `sum` while in substrait-java is named `sum:fp32`

If i print the `extensions.aggregateFunctions()` on the java side, I can see that all the functions include a data-type suffix: 
```
[bool_and:bool, bool_or:bool, count:any, count:, any_value:any, approx_count_distinct:any, sum:dec, avg:dec, min:dec, max:dec, sum:i8, sum:i16, sum:i32, sum:i64, sum:fp32, sum:fp64, sum0:i8, sum0:i16, sum0:i32, sum0:i64, sum0:fp32, sum0:fp64, avg:i8, avg:i16, avg:i32, avg:i64, avg:fp32, avg:fp64, min:i8, min:i16, min:i32, min:i64, min:fp32, min:fp64, min:ts, min:tstz, max:i8, max:i16, max:i32, max:i64, max:fp32, max:fp64, max:ts, max:tstz, product:i8, product:i16, product:i32, product:i64, product:fp32, product:fp64, std_dev:fp32, std_dev:fp64, variance:fp32, variance:fp64, corr:fp32_fp32, corr:fp64_fp64, mode:i8, mode:i16, mode:i32, mode:i64, mode:fp32, mode:fp64, median:req_i8, median:req_i16, median:req_i32, median:req_i64, median:req_fp32, median:req_fp64, quantile:req_req_i64_any, string_agg:str_str]
```

I don't know If I'm missing something or this is actually an issue. I wonder if this different mapping of functions between ibis and substrait-java is the reason why it is unable to map the `sum` function to a substrait java Plan when I call the `ProtoPlanConverter`. Do you know if there is a way/workaround to bypass this?

Note that if in the python side I create a plan that does not include any scalar/aggregate function, the plan is correctly loaded into a java substrait Plan.

**Comment by JosepSampe** [comment]
Is this related? https://github.com/ibis-project/ibis-substrait/issues/336

**Comment by gforsyth** [comment]
Hey @JosepSampe -- thanks for raising this, and apologies for the delay in response.  It's SciPy week and I've been running around.

The failure here is that substrait-java is expecting a slightly more strict version of function signature in the scalar function top-matter than ibis-substrait currently provides.  All of the consumers that ibis currently knows about (or that we've tested) discard or ignore the type information in the function signature.  I think there was a discussion about whether to simplify the spec on this front -- the information IS redundant, since the type information has to be included elsewhere in the plan, but having it present in the function signature allows for a faster compatibility check.

I'll raise this at the next Substrait community meeting and then either we'll add in the stricter signatures, or substrait-java will (hopefully) relax their checks slightly.

**Comment by gforsyth** [comment]
I wouldn't say we arrived at a definitive answer during the fortnightly meeting (notes are available https://docs.google.com/document/d/1Afg93ojsVWdwo3rBO2Dtng8__RYqAy_zJMrnqhTQapc/edit) but I think in the short- to medium-term, the better thing to do is for `ibis-substrait` to add in these compound function signatures.

**Comment by JosepSampe** [comment]
Thanks for digging into it @gforsyth. Looking forward to witnessing a potential solution for this.

**Comment by gforsyth** [comment]
Hey @JosepSampe -- cutting a release now with the compound function signatures implemented.

**Comment by JosepSampe** [comment]
Thank you so much @gforsyth!
