### ISSUE TITLE
Projection including the first column of a table results in empty value for 'field' field

### ISSUE THREAD

**Issue by thisisnic** [ibis-project/ibis-substrait#74]
I'm currently working on a package for creating substrait plans from R, and heavily leaning on the fantastic ibis-substrait for inspiration.  I'm implementing projection but am a bit confused by the numbering - wasn't sure if this is a bug or intentional.

In the tests in `test_compiler.py`, there's a table created via:
```
def t():
    return ibis.table(
        [
            ("full_name", "string"),
            ("age", "int64"),
            ("ts", "timestamp('UTC')"),
            ("delta", "interval"),
        ]
    )
```
and I've been experimenting with projection by calling:
```
expr = (t.projection(['full_name', 'age']))
result = translate(expr, compiler)
```
resulting in:
```
project {
  input {
    read {
      base_schema {
        names: "full_name"
        names: "age"
        names: "ts"
        names: "delta"
        struct {
          types {
            string {
              nullability: NULLABILITY_NULLABLE
            }
          }
          types {
            i64 {
              nullability: NULLABILITY_NULLABLE
            }
          }
          types {
            timestamp_tz {
              nullability: NULLABILITY_NULLABLE
            }
          }
          types {
            interval_day {
              nullability: NULLABILITY_NULLABLE
            }
          }
        }
      }
      named_table {
        names: "unbound_table_0"
      }
    }
  }
  expressions {
    selection {
      direct_reference {
        struct_field {
          child {
            struct_field {
            }
          }
        }
      }
    }
  }
  expressions {
    selection {
      direct_reference {
        struct_field {
          field: 1
          child {
            struct_field {
            }
          }
        }
      }
    }
  }
}
```
It makes sense that if 0-indexed, then the reference to the 'age' column results in the value '1' in the 'field' field 1, but there is no 'field' field for the 'full_name' column.  I just wanted to check if this is a bug or an expected value, as I'd have expected it to be there with a value of '0', though there may be a gap in my understanding here.

In some comments on another piece of code, a colleague of mine has commented "field indexes have to start at 1 because a value of 0 is the default protobuf value?" but I don't know what that means and they're not around right now - just mentioning in case it's relevant here!

**Comment by thisisnic** [comment]
Right, I got you, literally that it's the default value and so doesn't print; thanks for clarifying that!

**Comment by thisisnic** [comment]
Also, when you say "asking on the Substrait slack about zero-indexing for field offsets and default values in protobufs", how do you mean, sorry?

**Comment by cpcloud** [comment]
> Also, when you say "asking on the Substrait slack about zero-indexing for field offsets and default values in protobufs", how do you mean, sorry?

Ah, sorry for not being clear.

What I mean is asking whether having the semantics of "the default value is zero but also it means the 0th column" needs more discussion.
