### ISSUE TITLE
meta: ibis-substrait maintenance

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis-substrait#869]
**Acceptance criteria**: This meta-issue is for the roadmap to track required maintenance work for the `ibis-substrait` package in Q1 2024.

In general, this work is to ensure `ibis-substrait` is working with new releases of `ibis`. 

TODOs:

- [ ]

**Comment by lostmygithubaccount** [comment]
**Weekly Update**:
2024-01-18

- no update

(copying over last week's update on behalf of Gil)

**Comment by gforsyth** [comment]
* Bumped substrait-python to use substrait v0.42.0 and released.

**Comment by gforsyth** [comment]
* Bumped substrait-python to use substrait v0.42.1 and released.

**Comment by gforsyth** [comment]
* Fixed a bug in how we were translating group_bys with multiple grouping columns.

**Comment by gforsyth** [comment]
* Added support for Ibis 8.0

**Comment by gforsyth** [comment]
Bumped substrait-python to support 0.43.0 and released

**Comment by gforsyth** [comment]
* Bumped substrait-python to support 0.44.0 and released

**Comment by lostmygithubaccount** [comment]
closing out from last quarter
