### ISSUE TITLE
[EPIC] ibis-substrait maintenance

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis-substrait#870]
**Acceptance criteria**: This meta-issue is for the roadmap to track required maintenance work for the `ibis-substrait` package in Q2 2024.

In general, this work is to ensure `ibis-substrait` is working with new releases of `ibis`. 

TODOs:

- [ ]

**Comment by zhenzhongxu** [comment]
@gforsyth, Since the ibis 9.0 release, is ibis-substrate integration still fully functional? Also, what are the current plans moving this work forward, including Q3 as well?

**Comment by lostmygithubaccount** [comment]
Gil can speak to it better but I believe this effectively requires a full rewrite to upgrade to 9.0. I don't consider this a huge priority until required for whatever reason

Ibis 8.0 should still work
