### ISSUE TITLE
bug: group_by with multiple columns is interpreted as grouping sets

### ISSUE THREAD

**Issue by tokoko** [ibis-project/ibis-substrait#878]
### What happened?

normal `group_by` operation with multiple columns (something like this `group_by(["a", "b"])`) generates a plan that contains 
```
groupings {
  grouping_expressions {
    selection {
      direct_reference {
        struct_field {
        }
      }
      root_reference {
      }
    }
  }
}
groupings {
  grouping_expressions {
    selection {
      direct_reference {
        struct_field {
          field: 1
        }
      }
      root_reference {
      }
    }
  }
}
```

This is actually a grouping set, correct plan should have a single groupings entry containing multiple grouping_expressions.

### What version of ibis-substrait are you using?

2.29.1

### What substrait consumer(s) are you using, if any?

PyArrow

**Comment by gforsyth** [comment]
Thanks for reporting this @tokoko -- I'll take a look and see if we can get this sorted out.

**Comment by gforsyth** [comment]
Hey @tokoko ! I meant to follow up yesterday -- this is fixed and available in the latest release. Thanks for raising the issue!

**Comment by tokoko** [comment]
@gforsyth yup, checked and everything looks fine with the latest release. thanks for the quick fix.
